export const POST_PLACEHOLDERS = [
  "Como está a evolução do seu tumbling esta semana?",
  "Dica técnica para melhorar a estabilidade da base...",
  "Compartilhe um vídeo do seu novo elemento de stunt!",
  "Como você trabalha a flexibilidade para o scorpion?",
  "Qual o segredo para um basket toss com mais altura?",
  "Poste aqui o drill que mudou sua técnica de jumps.",
  "Como garantir um catching seguro em stunts de elite?",
  "Dicas para transições mais fluidas na rotina...",
  "Qual o melhor exercício de condicionamento para flyers?",
  "Como manter a energia do início ao fim do full out?",
  "Técnica de limpeza: como alinhar os braços em pirâmides?",
  "Qual o seu método para treinar a consciência corporal no ar?",
  "Compartilhe sua rotina de aquecimento favorita.",
  "Como evitar lesões comuns no tumbling?",
  "Qual a contagem mais desafiadora do seu show hoje?",
  "O que a liderança no cheer ensinou para sua vida profissional?",
  "Como gerir conflitos e manter a união da equipe?",
  "Dicas para treinadores: como dar feedbacks construtivos?",
  "Como atrair patrocinadores para o seu ginásio?",
  "Qual o papel da resiliência na carreira de um atleta?",
  "Como você organiza o cronograma de treinos da temporada?",
  "Insights sobre a gestão administrativa de equipes de cheer...",
  "O que você busca em um atleta ao montar um time de elite?",
  "Como equilibrar a cobrança técnica com o apoio emocional?",
  "A importância da formação acadêmica para profissionais do esporte.",
  "Como você analisa a planilha de pontuação após uma prova?",
  "Estratégias para manter a motivação da equipe no pós-competitivo.",
  "Qual o impacto do cheerleading no seu desenvolvimento pessoal?",
  "Compartilhe um marco importante na sua carreira como coach.",
  "Como fomentar a ética esportiva dentro do tatame?",
  "Qual meta você pretende alcançar na CheerConnect este mês?",
  "Conecte-se: marque alguém que te inspira tecnicamente.",
  "Como foi a experiência da sua última competição nacional?",
  "Qual conselho você daria para quem está começando no All-Star?",
  "Compartilhe uma conquista recente da sua equipe ou ginásio.",
  "Como você lida com a pressão pré-competição?",
  "Indique um curso ou certificação essencial para o mercado.",
  "O que não pode faltar na estrutura de um bom ginásio?",
  "Como a tecnologia tem ajudado seus treinos ultimamente?",
  "Compartilhe sua visão sobre o futuro do cheerleading no país.",
  "O que define o espírito de equipe para você?",
  "Qual a sua história de superação dentro deste esporte?",
  "Destaque um profissional que é referência em segurança no cheer.",
  "Como você trabalha a imagem do seu time nas redes sociais?",
  "Qual a importância do networking para crescer no cheerleading?",
  "Novidades no CheerConnect? Conte para a rede!",
  "Buscando novas parcerias para sua marca ou projeto?",
  "Como você utiliza o feedback dos juízes para evoluir?",
  "Poste aqui sua rotina favorita de todos os tempos.",
  "Qual o seu próximo passo profissional no mundo do cheer?",
];
